POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Robin King",
    "number": "123-456789"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Empty number"
}
###
GET  http://localhost:3001/api/persons